#ifndef CUSTOM_MINESWEEPER_MINESWEEPER_BOARDDATA_HPP_
#define CUSTOM_MINESWEEPER_MINESWEEPER_BOARDDATA_HPP_

struct BoardData {
	int height;
	int width;
	int mine_count;
};

#endif /* CUSTOM_MINESWEEPER_MINESWEEPER_BOARDDATA_HPP_ */
